/*
 * kernel/idt.h — Interrupt Descriptor Table.
 *
 * The IDT maps each of the 256 possible interrupt vectors to a handler.
 * In 64-bit mode each entry is 16 bytes (a 64-bit interrupt/trap gate).
 *
 * Gate descriptor layout (Intel SDM Vol.3A §6.14.1):
 *
 *   Bytes  0– 1: handler offset [15:0]
 *   Bytes  2– 3: segment selector (kernel code = 0x08)
 *   Byte       4: IST index (bits 2:0); bits 7:3 must be 0
 *   Byte       5: type + attributes
 *                  0x8E = 1000 1110 — P=1, DPL=0, type=0xE (64-bit interrupt gate)
 *                  Interrupt gates clear IF on entry (vs. trap gates which don't)
 *   Bytes  6– 7: handler offset [31:16]
 *   Bytes  8–11: handler offset [63:32]
 *   Bytes 12–15: reserved (must be 0)
 */

#ifndef IDT_H
#define IDT_H

#include <stdint.h>

/* A single 64-bit interrupt gate descriptor. */
typedef struct __attribute__((packed)) {
    uint16_t offset_lo;   /* Handler address bits [15:0]                   */
    uint16_t selector;    /* Code segment selector (must be 64-bit CS)     */
    uint8_t  ist;         /* IST slot (0 = use current stack; 1–7 = IST)  */
    uint8_t  type_attr;   /* Gate type + flags (0x8E for kernel int gate)  */
    uint16_t offset_mid;  /* Handler address bits [31:16]                  */
    uint32_t offset_hi;   /* Handler address bits [63:32]                  */
    uint32_t zero;        /* Reserved — must be zero                       */
} IDTEntry;

_Static_assert(sizeof(IDTEntry) == 16, "IDT entry must be 16 bytes");

/*
 * Populate all 256 IDT entries from the isr_stub_table generated by
 * isr_stubs.asm, then load the IDT with LIDT.
 */
void idt_init(void);

#endif /* IDT_H */
